version: '3.8'
services:
  gift-voucher-app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/src

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
