services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  db:
    image: "oscarfonts/h2"
    ports:
      - "9092:9092"
    environment:
      H2_OPTIONS: "-tcp -tcpAllowOthers -web -webAllowOthers"
